#### Import thư viện

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Bài tập: Cho các số a, b, m, n trong đó a < b là hai số thực bất kỳ; m, n là các số nguyên dương. Viết hàm số tạo một mảng hai chiều có shape = (m, n), các phần tử là các số ngẫu nhiên phân bố đều trong nửa đoạn [a, b).

In [ ]:
a = 1
b = 5
m = 3
n = 4
random_array = np.random.uniform(a, b, (m, n))
#Hiển thị mảng hai chiều với các phần tử là các số ngẫu nhiên phân bố đều
print(random_array)

[[3.00486038 3.27044181 4.67679081 3.27170508]
 [1.50843987 4.54687871 1.92077374 1.51167312]
 [1.48222478 4.80230517 1.97814094 2.6098614 ]]


In [ ]:
#Kiểm tra mảng trả về có đúng là mảng ngẫu nhiên các phần tử trong nửa đoạn [a,b)

#Tính kỳ vọng (mean) và phương sai (variance) của mảng
mean_array = np.mean(random_array)
variance_array = np.var(random_array)
print("Kỳ vọng của mảng: ", mean_array)
print("Phương sai của mảng: ", variance_array)

expected_mean = (b + a) / 2
expected_variance = ((b - a) ** 2) / 12
print("Kỳ vọng của biến ngẫu nhiên theo phân phối đều: ", expected_mean)
print("Phương sai của biến ngẫu nhiên theo phân phối đều: ", expected_variance)
#Nếu mảng được tạo ra chính xác theo phân phối đều trong nửa đoạn [a, b), thì kỳ vọng và phương sai của mảng sẽ
#gần bằng với kỳ vọng và phương sai của biến ngẫu nhiên theo phân phối đều.

Kỳ vọng của mảng:  2.8820079838687733
Phương sai của mảng:  1.4614441046534443
Kỳ vọng của biến ngẫu nhiên theo phân phối đều:  3.0
Phương sai của biến ngẫu nhiên theo phân phối đều:  1.3333333333333333


#### Bài tập: Cho các số a, s, m, n với:

* a là một số thực bất kỳ.
* s là một số thực dương.
* m, n là các số nguyên dương.
#### Xây dựng một mảng ngẫu nhiên hai chiều có shape = (m, n) mà các phần tử của nó tuần theo phân phối chuẩn có kỳ vọng bằng a và phương sai là s.

In [ ]:
a = 5.2  # Kỳ vọng
s = 6.7  # Phương sai
m = 5  # Số hàng
n = 4  # Số cột

#Tạo mảng
array_random = np.random.normal(a, np.sqrt(s), (m, n))
#Hàm np.random.normal(a, np.sqrt(s), size) tạo ra một mảng các số ngẫu nhiên tuân theo phân phối chuẩn với kỳ vọng là a và độ
#lệch chuẩn là căn bậc hai của phương sai (vì np.random.normal() yêu cầu đầu vào là độ lệch chuẩn chứ không phải phương sai).
print(array_random)

[[ 5.88781882  6.63615824  8.34709357  5.50329424]
 [ 6.70736098 -3.24381185 10.11482751  9.34525919]
 [ 5.77650529  2.16267715  5.92386328  3.6872047 ]
 [ 2.61175795  7.48001208  5.07204581  8.560973  ]
 [ 1.20660693  5.28363533  8.38784359  2.88133597]]
