# Phan Nguyễn Khôi Nguyên - 21068021

# 2.0. Mảng nhiều chiều

In [8]:
import numpy as np
a= np.array([[1, 2],
       [3, 4]])
#[1, 2] và [3, 4] thể hiện các hàng của ma trận (mảng 1 chiều)
print(a)

[[1 2]
 [3 4]]


# 2.1. Khởi tạo một ma trận

## 2.1.1. Khởi tạo một ma trận

In [10]:
import numpy as np
A = np.array([[1, 2], [3, 4]]) #Khởi tạo ma trận
A
#Lưu ý: nếu khai báo một mảng numpy ,nếu có ít nhất một phần tử của mảng là kiểu float thì tất 
#cả các phần tử trong mảng sẽ đều được coi là kiểu float

array([[1, 2],
       [3, 4]])

In [15]:
import numpy as np
B = np.array([[1, 2, 3], [4, 5, 6]], dtype = float) #dtype Chỉ định các phần tử trong mảng là kiểu float 
print(type(B[0][0]))

<class 'numpy.float64'>


In [16]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2.2. Ma trận đơn vị và ma trận đường chéo

## 2.2.1. Ma trận đơn vị

In [18]:
import numpy as np 
np.eye(3) #Tạo ma trận đơn vị có số chiều bằng 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
print(np.eye(3, k = 1)) #Với k=1 tạo đường chéo phụ phía trên đường chéo chính 1
print("\n")
print(np.eye(4, k= -2)) #Với k=-2 tạo đường chéo phụ phía dưới đường chéo chính 2


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## 2.2.2. Ma trận đường chéo

In [28]:
#np.diag Hàm này tạo ra một ma trận vuông có đường chéo chứa các phần tử 
#từ mảng đầu vào và các phần tử nằm ngoài đường chéo đều là 0.

print(np.diag([1, 3, 4])) 
#Do đầu vào là mảng 1 chiều nên trả về mảng 2 chiều thể hiện ma trận 
#có đường chéo lần lượt là các phần tử của mảng 1 chiều

print(np.diag(np.diag([1, 3, 4])))
#Do đầu vào là một mảng 2 chiều (có thể không vuông) nên trả về mảng 1
#chiều chứa các giá trị ở hàng thứ i


[[1 0 0]
 [0 3 0]
 [0 0 4]]
[1 3 4]


In [29]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(a)

np.diag(a, k = 1) #Lấy đường chéo phụ của ma trận a với k =1 là lấy trên
# ma trận chính 1 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 6])

In [33]:
import numpy as np
n=5
A= np.diag(np.arange(5),k=-1) 
print(A)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]]


# 2.3. Kích thước của ma trận

In [34]:
import numpy as np 
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(A)
print(A.shape) #Tương tự mảng 1 chiều ,tìm kích thức sử dụng .shape
#Trả ra kết quả là (3,4) với 3 là số hàng và 4 là số cột

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [39]:
#Tiếp tục sử dụng mảng A ở trên
print("Số hàng",A.shape[0]) #Trả ra số hàng
print("Số cột",A.shape[1]) #Trả ra số cột


Số hàng 3
Số cột 4


# 2.4. Truy cập vào từng phần tử của ma trận

## 2.4.1. Truy cập vào từng phần tử

### 2.4.1.1. Cách 1: giống với list

In [42]:
import numpy as np 
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(A[1][2]) #A[i][j] : trả về phần tử ở hàng i cột j của mảng A (chỉ số bắt đầu từ 0)

#A[1] chính lả mảng một chiều [4, 5, 6], trong mảng này, ta lấy phần tử 
#có chỉ số là 2, phần tử đó có giá trị là 6. Vậy A[1][2] = 6.

6


### 2.4.1.2. Cách 2: giống như Matlab

In [43]:
import numpy as np 
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(A[2, 1]) #Tương tự như trên nhưng bộ chỉ số sẽ được đặt trong dấu ngoặc vuông []
#Trả về phần tử của mảng A ở hàng 2 cột 1 ==> 8

8


# 2.4.2. Truy cập vào hàng/cột

In [45]:
#Sử dụng lại mảng A ở bài trên
print(A[2]) #In ra hàng thứ 2 của mảng A(cách 1)
print(A[0,:]) #In ra hàng thứ 0 của mảng A(cách 2) 

[7 8 9]
[1 2 3]


In [47]:
#Sử dụng lại mảng A ở bài trên
print(A[:, 1]) #In ra cột thứ 1 của mảng A

[2 5 8]


In [55]:
import numpy as np
A = np.array([
    [1, 2], 
    [3, 4]
])

def myfunc(a):
    maTranCot =[x for x in a[:,np.arange(0,a.shape[1],2)]]
    print(np.sum(maTranCot))
myfunc(A)

4


# 2.5. Truy cập vào nhiều phần tử của ma trận

## 2.5.1. Nhiều phần tử trong cùng một hàng

In [56]:
import numpy as np 
A = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
print(A)
A[0, 2:] #Lấy hàng đầu tiên (hàng 0) và lấy từ cột thứ 2 đến hết
A[1, range(0, A.shape[1], 2)] # in ra phần tử ở hàng 1 cột 0 và hàng 1 cột 2
#range(0, A.shape[1], 2):Tạo mảng từ 0 đến 3 (A.shape[1] = 4) với bước nhảy là 2 ==> [0,2]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([5, 7])

## 2.5.2. Nhiều phần tử trong cùng một cột

In [58]:
#Sử dụng lại mảng A ở bài trên
A[[0, 2], -1] 
#In ra phẩn tử ở hàng 0 cột -1 (cột cuối)và phần tử ở hàng 2 cột -1 (cột cuối)

array([ 4, 12])

## 2.5.3. Nhiều hàng, nhiều cột

In [63]:
#Sử dụng lại mảng A ở bài trên
print(A)
print(A[[1, 2]][:, [0,3]])

#A[[1, 2]][:, [0,3]] : đầu tiên lấy hai hàng có chỉ số 1 và 2 bằng A[[1, 2]], ta được một
#ma trận, sau đó lấy hai cột có chỉ số 0 và 3 của ma trận mới này.
##Khác với
print(A[[1, 2], [0, 3]]) 
#Đầu tiên lấy 2 hàng  1 và 2 sau đó lấy cột 0 của hàng 1 rồi lấy cột 3 của hàng 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  8]
 [ 9 12]]
[ 5 12]


## 2.5.4. Cặp các toạ độ

In [64]:
print(A[[1, 2], [0, 3]]) 

[ 5 12]


In [66]:
#Sử dụng lại mảng A ở bài trên
print(A)
A[[1, 2], [0]] #[1, 2], [0] là list các tọa độ theo mỗi chiều
#Do [0] là list có độ dài bằng 1 do đó nó sẽ cặp với mọi phần tử của list còn lại
#==>Kết quả trả ra sẽ là hàng 1 cột 0 và hàng 2 cột 0

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([5, 9])

In [93]:
import numpy as np 
A = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
print(A)

def myfunc(a):
    tong = 0
    for i in np.arange(0, a.shape[0], 2):
        for j in np.arange(0, a.shape[1], 2):
            tong += a[i][j]
    return tong

print(myfunc(A))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
24


In [99]:
#Cách 2
import numpy as np 
A = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
print(A)

def myfunc(a):
    A= a[np.arange(0, a.shape[0], 2)][:,np.arange(0, a.shape[1], 2)]
    print(np.sum(A))

myfunc(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 2]
[0 2]
24


# 2.6. np.sum, np.min, np.max, np.mean cho mảng nhiều chiều

In [2]:
import numpy as np
A = np.array([
    [1., 2, 3, 2], #Do có 1 phần tử ở đây là kiểu float ==> tất cả các phần tử đều là kiểu float
    [4, 3, 7, 4], 
    [1, 4, 2, 3]])
print(A)

[[1. 2. 3. 2.]
 [4. 3. 7. 4.]
 [1. 4. 2. 3.]]


In [10]:
print(A)
print("Mảng chứa tổng của từng cột trong A là: ",np.sum(A, axis = 0))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là tổng từng cột của A

print("Mảng chứa giá trị nhỏ nhất của từng cột trong A là: ", np.min(A, axis = 0))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị nhỏ nhất từng cột của A

print("Mảng chứa giá trị lớn nhất của từng cột trong A là: ",np.max(A, axis = 0))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị lớn nhất từng cột của A

print("Mảng chứa giá trị trung bình của từng cột trong A là: ",np.mean(A, axis = 0))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị trung bình từng cột của A

[[1. 2. 3. 2.]
 [4. 3. 7. 4.]
 [1. 4. 2. 3.]]
Mảng chứa tổng của từng cột trong A là:  [ 6.  9. 12.  9.]
Mảng chứa giá trị nhỏ nhất của từng cột trong A là:  [1. 2. 2. 2.]
Mảng chứa giá trị lớn nhất của từng cột trong A là:  [4. 4. 7. 4.]
Mảng chứa giá trị trung bình của từng cột trong A là:  [2. 3. 4. 3.]


In [11]:
#Tương tự như thế khi thay axis = 1, kết quả trả về được tính theo hàng

print("Mảng chứa tổng của từng hàng trong A là: ",np.sum(A, axis = 1))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là tổng từng hàng của A

print("Mảng chứa giá trị nhỏ nhất của từng hàng trong A là: ", np.min(A, axis = 1))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị nhỏ nhất từng hàng của A

print("Mảng chứa giá trị lớn nhất của từng hàng trong A là: ",np.max(A, axis = 1))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị lớn nhất từng hàng của A

print("Mảng chứa giá trị trung bình của từng hàng trong A là: ",np.mean(A, axis = 1))
#Kết quả trả về là 1 mảng ,với mỗi phần tử là giá trị trung bình từng hàng của A


Mảng chứa tổng của từng hàng trong A là:  [ 8. 18. 10.]
Mảng chứa giá trị nhỏ nhất của từng hàng trong A là:  [1. 3. 1.]
Mảng chứa giá trị lớn nhất của từng hàng trong A là:  [3. 7. 4.]
Mảng chứa giá trị trung bình của từng hàng trong A là:  [2.  4.5 2.5]


In [13]:
#Nếu không truyền vô axis thì kết quả sẽ được tính trên toàn bộ ma trận

print("Tổng của ma trận A là: ",np.sum(A))

print("Gía trị nhỏ nhất của ma trận A là: ", np.min(A))

print("Gía trị lớn nhất của ma trận A là: ",np.max(A))

print("Gía trị trung bình của ma trận A là: ",np.mean(A))

Tổng của ma trận A là:  36.0
Gía trị nhỏ nhất của ma trận A là:  1.0
Gía trị lớn nhất của ma trận A là:  7.0
Gía trị trung bình của ma trận A là:  3.0


### keepdims = True

In [16]:
print(np.sum(A, axis = 0, keepdims = True)) #keepdims=True: Giữ chiều của kết quả.
print("\n")
print(np.mean(A, axis = 1, keepdims = True)) #keepdims=True: Giữ chiều của kết quả.

[[ 6.  9. 12.  9.]]


[[2. ]
 [4.5]
 [2.5]]


In [17]:
import numpy as np
A = np.array([
    [1., 2, 3, 2],
    [4, 3, 7, 4], 
    [1, 4, 2, 3]])
print(A)

def myfunc(a):
    min_arr = np.min(a, axis = 1)
    max_arr = np.max(a, axis = 1)
    biendong= max_arr - min_arr
    print(np.sum(biendong))
myfunc(A)

[[1. 2. 3. 2.]
 [4. 3. 7. 4.]
 [1. 4. 2. 3.]]
9.0


# 2.7. Các phép toán tác động đến mọi phần tử của ma trận

## 2.7.1. Tính toán giữa một mảng hai chiều và một số vô hướng

In [20]:
import numpy as np 
A = np.array([[1, 3], [2, 5]])
print(A)

print(A + 2)

print(A*2)

print(2**A)
#Từng phần tử của mảng sẽ được kết hợp với số vô hướng bằng các phép toán tương ứng để tạo 
#ra một mảng mới cùng kích thước

[[1 3]
 [2 5]]
[[3 5]
 [4 7]]
[[ 2  6]
 [ 4 10]]
[[ 2  8]
 [ 4 32]]


## 2.7.2. np.abs, np.sin, np.exp, …

A = np.random.randn(2, 3) # create a random numpy array with shape = (2, 3)
print(A)

np.abs(A) #tính trị tuyệt đối của numpy A


In [32]:
A = np.array([
    [1, 3], 
    [2, 5]]
)
print(A)

def norm_fro(A):
    a= A ** 2 #Từng phần tử bình phương
    print(np.sqrt(np.sum(a))) #Căn tất cả
    
norm_fro(A)

[[1 3]
 [2 5]]
6.244997998398398


# 2.8. Các phép toán giữa hai ma trận I

In [35]:
import numpy as np 
A = np.array([[1., 5], [2, 3]])
B = np.array([[5., 8], [7, 3]])
print(A*B) #Nhân theo từng cặp cùng chỉ số

print(A**B) #Mũ theo từng cặp cùng chỉ số

[[ 5. 40.]
 [14.  9.]]
[[1.00000e+00 3.90625e+05]
 [1.28000e+02 2.70000e+01]]


In [9]:
#Tính bình phương Frobenious norm của hiệu hai ma trận
import numpy as np 
A = np.array([[1., 5], [2, 3]])
B = np.array([[5., 8], [7, 3]])

def norm_fro(A):
    a= A ** 2 #Từng phần tử bình phương
    fn= np.sqrt(np.sum(a)) #Căn tất cả
    return fn
    
def dist_fro(A,B):
    diff = A -B
    print(norm_fro(diff)**2)
    
dist_fro(A,B)

50.00000000000001


# 2.9. Chuyện vị ma trận, Reshape ma trận

## 2.9.1 Chuyển vị ma trận

In [11]:
import numpy as np 
A = np.array([[1, 2, 3],[4, 5, 6]])
print("Ma trận gốc",A)

print("Ma trận chuyển vị", A.T) #Cách 1

print("Ma trận chuyển vị",np.transpose(A)) #Cách 2

Ma trận gốc [[1 2 3]
 [4 5 6]]
Ma trận chuyển vị [[1 4]
 [2 5]
 [3 6]]
Ma trận chuyển vị [[1 4]
 [2 5]
 [3 6]]


## 2.9.2. Reshape

In [15]:
print(A)
print(np.reshape(A, (3, 2)))

print(A.reshape(3, 2))


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(A)

print(np.reshape(A, 6)) #Thay đổi mảng A thành  mảng 1 chiều

print(A.reshape(3, 1, 2)) #Thay đổi mảng A thành mảng 3 chiều
#Tạo 3 khối mỗi khối chứa 1 dòng và có 2 cột

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [22]:
print(A.reshape(-1)) #-1 python sẽ tự tìm ra kích thước phù hợp để tạo mảng 1 chiều

print(np.reshape(A, (6, -1))) #-1 là kích thước do python tự tìm ra giúp mik

#Tương tự nếu với mảng 3 chiều thì phải cho biết trước 2 số và số còn lại python sẽ tự tính

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## 2.9.3. Thứ tự của phép toán reshape

In [25]:
print(A)

A.reshape(3, -1, order = 'F')  #Nếu order là F thì đi từ cột rồi tới dòng.Thay đổi kích thước là 3 dòng và cột do python tính

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
import numpy as np 
A = np.arange(1, 13).reshape(3,4).reshape(4,-1,order='F')
print(A.T)


[[ 1  5  9  2]
 [ 6 10  3  7]
 [11  4  8 12]]


# 2.10. Các phép toán giữa ma trận và vector

In [78]:
import numpy as np 
A = np.arange(12).reshape(3, -1) #Tạo mảng có 3 dòng và cột do python tính (mảng 2 chiều)
print(A)

b = np.array([1., 2, 3, 5]) #Tạo mảng 1 chiều b
print(b)

print(A + b) #Thực hiện phép tính giữa mảng 2 chiều và 1 chiều
#Kết quả thu được bằng cách lấy từng hàng của A cộng cho b

print(A*b)  #Thực hiện phép tính giữa mảng 2 chiều và 1 chiều
#Kết quả thu được bằng cách lấy từng hàng của A nhân cho b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1. 2. 3. 5.]
[[ 1.  3.  5.  8.]
 [ 5.  7.  9. 12.]
 [ 9. 11. 13. 16.]]
[[ 0.  2.  6. 15.]
 [ 4. 10. 18. 35.]
 [ 8. 18. 30. 55.]]


In [79]:
c = np.array([1, 2, 1,2])
A**c
#Cách thực hiện cũng tương tự với phép mũ

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

In [84]:
import numpy as np

def zero_mean(X):
    tb_Row = np.mean(X, axis= 1,keepdims=True)
    result = X - tb_Row
    return result

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(zero_mean(X))

#chuẩn hoá zero-mean, tức là giá trị trung bình của mỗi hàng là 0.

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 2.11. Tích giữa hai ma trận, tích giữa ma trận và vector

## 2.11.1. Tích giữa hai ma trận

In [88]:
import numpy as np 
A = np.arange(12).reshape(4, 3)
print(A)

B = np.arange(-5, 7).reshape(3,-1)
print(B)

print("Tích của 2 ma trận là :",A.dot(B))  #Tích của 2 ma trận A và B
# Khác với A*B vì * dùng cho 2 ma trận có cùng kích thước (nhân theo từng cặp phần tử)

print("Tích của 2 ma trận là :",np.dot(A, B)) #Một cách khác khi tính tích của 2 ma trận A và B

#Tích của hai ma trận được tính bằng cách nhân từng phần tử của hàng trong ma trận thứ nhất với từng 
#phần tử của cột trong ma trận thứ hai và sau đó cộng các tích này lại với nhau.

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]
Tích của 2 ma trận là : [[  5   8  11  14]
 [ -4   8  20  32]
 [-13   8  29  50]
 [-22   8  38  68]]
Tích của 2 ma trận là : [[  5   8  11  14]
 [ -4   8  20  32]
 [-13   8  29  50]
 [-22   8  38  68]]


## 2.11.2. Tích giữa một ma trận và một vector

In [97]:
print(A)
b = np.array([1, 3, 4])
print(b)

print(A.dot(b)) #Kết quả trả về là một mảng một chiều có shape[0] == 4

print(A*b) # = b*A



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 3 4]
[11 35 59 83]
[[ 0  3  8]
 [ 3 12 20]
 [ 6 21 32]
 [ 9 30 44]]


In [ ]:
b.dot(A) #Bị lỗi do xung đột chiều (vì b được koi mà vector hàng)

c = np.array([1, 2, 3, 4])
c.dot(A)  #Thực hiện được (vì c được koi là vector hàng)


In [100]:
import numpy as np

def fro_trace(X):
    tich = X.dot(X.T)
    return np.trace(tich)

A = np.array([
    [1, 3], 
    [2, 5]]
)
print(fro_trace(A))

39


# 2.12. Softmax III - Phiên bản tổng quát

In [104]:
import numpy as np 
A = np.arange(12).reshape(4, 3)
print(A)
def softmax(A):
    return np.exp(A - np.reshape(np.max(A, axis=1),(A.shape[0],-1))) / np.sum(np.exp(A - np.reshape(np.max(A, axis=1),(A.shape[0],-1))))

result = softmax(A)
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0.02250764 0.06118212 0.16631024]
 [0.02250764 0.06118212 0.16631024]
 [0.02250764 0.06118212 0.16631024]
 [0.02250764 0.06118212 0.16631024]]
