# Phan Nguyễn Khôi Nguyên - 21068021

# 1.1 Khởi tạo mảng 1 chiều

## 1.1.1. Khai báo vector

In [3]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 1.2. Kiểu dữ liệu của mảng

## 1.2.1 Kiểu dữ liệu

In [9]:
import numpy as np
a = np.array([1, 2])
print(type(a[0]))  #các phần tử trong mảng là kiểu nguyên

<class 'numpy.int32'>


In [11]:
a = np.array([1.0, 2.0]) #Tạo mảng có các phần tử là số thực
 # or np.array([1., 2.]) or np.array([1., 2])
print(type(a[0]))  #Các phần tử trong mảng là kiểu số thực "numpy.float64"

<class 'numpy.float64'>


In [12]:
a = np.array([1, 2], dtype = np.float64)  #dtype để ép kiểu kiểu
print(type(a[0])) #Các phần tử trong mảng là kiểu số thực "numpy.float64"

<class 'numpy.float64'>


# 1.3. Khởi tạo các mảng một chiều đặc biệt

## 1.3.1. Mảng toàn giá trị 0 hoặc 1

In [17]:
import numpy as np 
np.zeros(3) #dùng để tạo vector 0 có số phần tử là 3, các phần tử là kiểu số thực

array([0., 0., 0.])

In [18]:
import numpy as np 
np.ones(3) #dùng để tạo vector 1 có số phần tử là 3, các phần tử là kiểu số thực

array([1., 1., 1.])

In [20]:
x = np.array([1, 2, 3])
zero= np.zeros_like(x) #zeros_like: Tạo mảng chứa các giá trị 0 và có số chiều như mảng đầu vào 
one= np.ones_like(x)   #ones_like: Tạo mảng chứa các giá trị 1 và có số chiều như mảng đầu vào
print(zero)
print(one)

[0 0 0]
[1 1 1]


## 1.3.2. Cấp số cộng

In [21]:
np.arange(3) #Tạo mảng các số nguyên từ 0 đến n-1 (ở đây là tạo mảng từ 0 đến 2)

array([0, 1, 2])

In [23]:
 np.arange(3, 6) #Tương tự như trên nhưng ở đâu có thêm 1 giá trị đầu vào. Tức là sẽ tạo mảng từ 3 đến 6-1

array([3, 4, 5])

Hàm np.arange(a, b, d) trong NumPy được sử dụng để tạo ra một mảng các số có giá trị từ a đến b (không bao gồm b), với bước nhảy là d. Cụ thể, giá trị đầu tiên của mảng sẽ là a, và mỗi giá trị tiếp theo sẽ tăng thêm d so với giá trị trước đó cho đến khi giá trị cuối cùng trong mảng không vượt quá hoặc bằng b.

In [24]:
np.arange(0, 1, 0.1)
#Tạo mảng từ 0 đến nhỏ hơn 1 với bước nhảy là 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [25]:
np.arange(5, 1, -0.9)
# Tạo Mảng bắt đầu từ 5, giảm đi 0.9 để đạt được giá trị tiếp theo
# và tiếp tục như vậy cho đến khi giá trị dưới 1.0
#Vì d (-0.9) là số âm và b (1) nhỏ hơn a (5), nên phần tử cuối cùng 
# của dãy số sẽ là phần tử nhỏ nhất của cấp số cộng, và giá trị đó là 1.4.

array([5. , 4.1, 3.2, 2.3, 1.4])

In [29]:
import numpy as np

# Tạo mảng các luỹ thừa của 2 nhỏ hơn 1025
exponents = np.arange(11)  # 2^0 đến 2^10

powers_of_two = 2 ** exponents
#2 là một số và exponents là một mảng do đó powers_of_two là mảng có cùng
#kích thước với exponents và mỗi phần tử sẽ là 2 mũ lên.
print(powers_of_two)

[   1    2    4    8   16   32   64  128  256  512 1024]


In [30]:
import numpy as np
# Tạo mảng gồm 10 phần tử
my_array = np.full(10, 3)  #np.full:Tạo mảng với 10 phần tử, mỗi phần tử có giá trị là 3
my_array[-1] = 1.5  # Gán giá trị 1.5 cho phần tử cuối cùng của mảng
print(my_array)

[3 3 3 3 3 3 3 3 3 1]


# 1.4. Truy cập mảng một chiều

## 1.4.1. Kích thước của mảng

In [51]:
x = np.array([3, 4, 5])
print(x.shape) #(3,) cho biết rằng mảng x có 3 phần tử và chỉ có một chiều.

d = x.shape[0] # 
print(d) #để lấy phần tử đầu tiên và duy nhất của tuple (số phần tử của x)

(3,)
3


## 1.4.2. Chỉ số

## 1.4.3. Đọc từng phần tử của vector

In [61]:
x = np.array([1, 3, 2])
print(x)
print(x[0]) # Phần tử đầu tiên của mảng x. Muốn lấy các phần tử tiếp theo thì tăng dần lên như x[1], x[2],...

[1 3 2]
1


In [62]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 1.4.5. Thay đổi giá trị một phần tử của mảng

In [63]:
a = np.array([1, 2, 3])
a[0] = 4 #Thay đổi phần tử đầu tiên trong mảng a bằng 4
print(a) # in mảng a để xem kết quả

[4 2 3]


In [64]:
def replace_with_mean(arr):
    # Tính trung bình cộng của các phần tử trong mảng
    mean_value = sum(arr) / len(arr)
    #sum(arr) : tính tổng các phần tử trong arr
    #len(arr) : tổng độ dài trong arr (số phần tử của arr)
    # Thay toàn bộ các phần tử bằng trung bình cộng
    for i in range(len(arr)): #range(len(arr) : chạy từ 0 đến len(arr) -1
        arr[i] = mean_value

# Ví dụ sử dụng
my_array = [1, 2, 3, 4, 5]
print("Mảng trước khi thay đổi:", my_array)

replace_with_mean(my_array) #Hàm này thay đổi trực tiếp my_array mà không tạo ra mảng mới

print("Mảng sau khi thay đổi:", my_array)


Mảng trước khi thay đổi: [1, 2, 3, 4, 5]
Mảng sau khi thay đổi: [3.0, 3.0, 3.0, 3.0, 3.0]


# 1.5. Truy cập nhiều phần tử của mảng một chiều

## 1.5.1. Đọc

In [74]:
import numpy as np
a = 0.5*np.arange(10) #Tạo một numpy.ndarray từ 0 đến 9 mỗi phần tử nhân với 0.5
print(a)

ids = [1, 3, 4, 8] #Tạo list với 4 phần tử
print(a[ids]) #Trả về mảng numpy với các phần tử có chỉ số được chỉ ra trong list các chỉ số ids
#Tương tự cũng có thể là mảng numpy chứa các số nguyên hợp lệ
np_ids = np.arange(1, 7, 2) #1 3 5
print(a[np_ids])

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.5 2.  4. ]
[0.5 1.5 2.5]


In [78]:
import numpy as np
a = 0.5*np.arange(10) #Tạo một numpy.ndarray từ 0 đến 9 mỗi phần tử nhân với 0.5
print("Mảng a là: ", a)
print(a[:3]) # trả về mảng các phần tử của a với chỉ số từ đầu đến 3-1
print(a[-3:]) # trả về mảng các phần tử của a với chỉ số từ dưới đếm lên 3 số đến hết
print(a[1:4]) # trả về mảng các phần tử của a với chỉ số từ 1 đến 4-1


Mảng a là:  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 1. ]
[3.5 4.  4.5]
[0.5 1.  1.5]


## 1.5.2. Ghi

In [84]:
import numpy as np
a = 0.5*np.arange(10) #Tạo một numpy.ndarray từ 0 đến 9 mỗi phần tử nhân với 0.5
print("Mảng a là: ", a)

a[[1, 3, 5]] = 1 #Thay đổi a[1], a[3], a[5] = 1
print(a)

a[-3:] = np.array([0, -1, -2]) #Thay đổi 3 phần tử cuối của mảng a lần lượt là 0, -1, -2
print(a)

#a[::2] Được sử dụng để lấy 1 phần của mảng a với 1 bước nhảy là 2,tức là chỉ lấy các phần tử có chỉ số chắn
print(a[::2])

#a[::-1] Các phần tử được lấy từ cuối mảng đến đầu mảng, với bước là -1.Bước âm có nghĩa là di chuyển ngược
print(a[::-1])

Mảng a là:  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  1.  1.  1.  2.  1.  3.  3.5 4.  4.5]
[ 0.  1.  1.  1.  2.  1.  3.  0. -1. -2.]
[ 0.  1.  2.  3. -1.]
[-2. -1.  0.  3.  1.  2.  1.  1.  1.  0.]


In [98]:
import numpy as np
n=4
mang= np.zeros(n)
#Cập nhật các phần tử có chỉ số chẵn
mang[::2] = 2 + np.arange(n // 2) * -0.5
#Cập nhật các phần tử có chỉ số lẻ
mang[1::2] = -1
print(mang)


[ 2.  -1.   1.5 -1. ]


# 1.6. Tính toán giữa các mảng một chiều và số vô hướng

## 1.6.1. Phép toán giữa mảng một chiều với một số vô hướng.

In [101]:
x = np.array([1, 2, 3])
a = 3  
x + a #Cộng mọi phần tử (tất cả) trong mảng 1 chiều a với x 
#Tương tự với +, -, x, /, **

array([4, 5, 6])

## 1.6.2. Phép toán giữa hai mảng một chiều

In [106]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x*y) #Lấy từng cặp phần tử tương ứng của hai mảng để tính toán rồi lấy kết quả.Trả về số phần tử như nhau
#Tương tự với +, -, x, /, **
#Lưu ý số phần tử của 2 mảng phải như nhau
print(x ** y)

[ 4 10 18]
[  1  32 729]


## 1.6.3. Các hàm toán học

In [114]:
import numpy as np

def calculate_sum_z(x):
   y= np.pi/2 - x
   print(y)
   z= np.cos(x) -np.sin(x)
   print(np.sum(z))
# Ví dụ sử dụng
x = np.array([1,5,7,9,6,10])
calculate_sum_z(x)

[ 0.57079633 -3.42920367 -5.42920367 -7.42920367 -4.42920367 -8.42920367]
0.6596200563468989


# 1.7. Norm 1

In [117]:
import numpy as np
x = np.array([1,5,7,9,6,10])
x_abs= np.abs(x)
print(np.sum(x_abs)) #In ra norm 1 của x

38


# 1.8. Hàm Softmax cho mảng một chiều

In [120]:
import numpy as np
sm = np.array([1.0, 2.0, 3.0,4.0,5.0])
def softmax(z):
    exp_z = np.exp(z) #Trả về e mũ của từng phần tử trong mảng x
    sum_exp_z = np.sum(exp_z) # Tính tổng của tất cả các giá trị mũ e
    softmax_result = exp_z / sum_exp_z #Công thức tính softmax
    return softmax_result
print(softmax(sm))

[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]


# 1.9. Tích vô hướng của hai vectors - Norm 2

In [123]:
import numpy as np 
x = np.arange(3) #Tạo mảng x có 3 phần tử từ 0 đến 2
y = np.ones(3)  #Tạo mảng y có 3 phần tử đều là số 1.Kiểu số thực
np.sum(x*y) #Tính tích vô hướng .Lưu ý phải dùn cho 2 vector có cùng số phần tử 

3.0

In [124]:
x, y = np.arange(3), np.ones(3)
x.dot(y)  #Cách khác dùng .dot để tính tích vô hướng hoặc np.dot(x, y)


3.0

In [133]:
#Cách 1:
import numpy as np
v = np.array([3, 4,7]) #Tạo mảng 1 chiều v
def calulate_norm_2(x):
    #tính tổng bình phương các phần tử
    sum_binhPhuong = np.sum(x ** 2)
    print(np.sqrt(sum_binhPhuong))

calulate_norm_2(v)

8.602325267042627


In [132]:
#Cách 2
import numpy as np
v = np.array([3, 4,7]) #Tạo mảng 1 chiều v
norm_2 = np.linalg.norm(v)
print(norm_2)

8.602325267042627


# 1.10. min, max, armin, argmax của mảng một chiều

## 1.10.1. min, max

In [137]:
import numpy as np 
a = np.arange(10) #Tạo mảng a có 10 phần tử tử 0 đến 9
a[-1] = -2 #Thay đổi giá trị cuối cùng của mảng a là -2

print(np.min(a)) #Tìm giá trị nhỏ nhất của mảng a hoặc a.min()
print(np.max(a)) #Tìm giá trị lớn nhất của mảng a hoặc a.max()


-2
8


## 1.10.2. argmin, argmax

In [138]:
#Sử dụng tiếp mảng a ở trên
# a= [ 0  1  2  3  4  5  6  7  8 -2]
print(np.argmin(a)) #Phần tử nhỏ nhất là -2 có chỉ số là 9  hoặc có thể dùng a.argmin()
print( np.argmax(a)) #Phần tử lớn nhất là 8 có chỉ số là 8 hoặc có thể dùng a.argmax()

[ 0  1  2  3  4  5  6  7  8 -2]
9
8


In [139]:
import numpy as np

def predict_class(probabilities):
    # Sử dụng np.argmax để tìm chỉ số của phần tử có giá trị lớn nhất
    predicted_class_index = np.argmax(probabilities)
    return predicted_class_index


probabilities = np.array([0.2, 0.6, 0.1, 0.1]) #Tạo 1 mảng xác xuất mẫu

predicted_class = predict_class(probabilities)
print("Predicted class index:", predicted_class) #Xác xuất cao nhất là 0.6 ở vị trí số 1

Predicted class index: 1


# Softmax II - Phiên bản ổn định

In [144]:
import numpy as np

def softmax_Moi(z):
    c = np.max(z) #giá trị lớn nhất của mảng z
    exp_z = np.exp(z - c)
    # Tính softmax ổn định
    softmax_result = exp_z / np.sum(exp_z)
    return softmax_result
    
def softmax_Cu(z):
    exp_z = np.exp(z) #Trả về e mũ của từng phần tử trong mảng x
    sum_exp_z = np.sum(exp_z) # Tính tổng của tất cả các giá trị mũ e
    softmax_result = exp_z / sum_exp_z #Công thức tính softmax
    return softmax_result

z = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

result_stable = softmax_Moi(z)
print("Softmax Stable Result:", result_stable)

# Gọi hàm softmax và in kết quả (so sánh với hàm softmax trước đây)
result_original = softmax_Cu(z)
print("Original Softmax Result:", result_original)

Softmax Stable Result: [0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
Original Softmax Result: [0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]


In [143]:
import numpy as np

def softmax_Moi(z):
    c = np.max(z) #giá trị lớn nhất của mảng z
    exp_z = np.exp(z - c)
    # Tính softmax ổn định
    softmax_result = exp_z / np.sum(exp_z)
    return softmax_result
    
def softmax_Cu(z):
    exp_z = np.exp(z) #Trả về e mũ của từng phần tử trong mảng x
    sum_exp_z = np.sum(exp_z) # Tính tổng của tất cả các giá trị mũ e
    softmax_result = exp_z / sum_exp_z #Công thức tính softmax
    return softmax_result

z = np.array([1000.0, 2000.0, 3000.0, 4000.0, 5000.0])

result_stable = softmax_Moi(z)
print("Softmax Stable Result:", result_stable)

# Gọi hàm softmax và in kết quả (so sánh với hàm softmax trước đây)
result_original = softmax_Cu(z)
print("Original Softmax Result:", result_original)

#Ví dụ trên cho thấy score vector z chứa các số lớn, và bạn có thể thấy rõ sự khác biệt giữa
#kết quả của hàm softmax và softmax_stable. Khi sử dụng hàm softmax,có thể gặp vấn đề tràn số
#trong khi hàm softmax_stable giữ được tính ổn định

Softmax Stable Result: [0. 0. 0. 0. 1.]
Original Softmax Result: [nan nan nan nan nan]


C:\Users\Khoi Nguyen\AppData\Local\Temp\ipykernel_4148\992778302.py:11: RuntimeWarning: overflow encountered in exp
  exp_z = np.exp(z) #Trả về e mũ của từng phần tử trong mảng x
C:\Users\Khoi Nguyen\AppData\Local\Temp\ipykernel_4148\992778302.py:13: RuntimeWarning: invalid value encountered in divide
  softmax_result = exp_z / sum_exp_z #Công thức tính softmax
